[profile.default]
src = "src"
out = "out"
libs = ["lib"]

[rpc_endpoints]
base = "https://base-mainnet.g.alchemy.com/v2/e1_GmDaAKAqFl4HPuV9bZBEq5l7fdJEY"
base-sepolia = "https://base-sepolia.g.alchemy.com/v2/e1_GmDaAKAqFl4HPuV9bZBEq5l7fdJEY"

#e1_GmDaAKAqFl4HPuV9bZBEq5l7fdJEY
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
