[profile.default]
src = "src"
out = "out"
libs = ["lib"]

remappings = [
    "@openzeppelin/=lib/openzeppelin-contracts/",
    "forge-std/=lib/forge-std/src/"
]

[rpc_endpoints]
base = "${ALCHEMY_BASE_MAINNET_URL}"
base-sepolia = "${ALCHEMY_BASE_SEPOLIA_URL}"